---
title: "Nowcasting infectious disease dynamics - SISMID"
site: distill::distill_website
comments: false
about:
  template: jolla
  links:
    - icon: chat-fill
      text: Dive into the course
      href: sessions/introduction-and-course-overview.html
    - icon: github
      text: Visit us on GitHub
      href: https://github.com/nfidd/sismid-nowcasting
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

A course and living resource for learning about nowcasting of infectious disease dynamics, originally developed by the [nfidd](https://nfidd.github.io/nfidd) team and adapted for [SISMID](https://sismid.sph.emory.edu/).

This course runs in the **first half of the SISMID week (Monday to Wednesday midday)** and covers delay distributions, biases in delays, the renewal equation and $R_t$ estimation, and nowcasting, building up to a bridge into forecasting.

It is one of a pair of SISMID courses: this **Nowcasting & $R_t$ estimation** course covers the first half of the week, and the companion [Forecasting & evaluation](https://nfidd.github.io/sismid-forecasting/) course covers the second half. See the [umbrella SISMID course](https://nfidd.github.io/sismid/) for the combined material.

We invite anyone to use the materials here in their own teaching and learning. For questions and discussion of the course or its content, we welcome all users to the [Discussion board](https://github.com/nfidd/sismid-nowcasting/discussions). We welcome all forms of [contributions, additions and suggestions](https://github.com/nfidd/sismid-nowcasting/issues) for improving the materials.

All materials here are provided under the permissive [MIT License](https://github.com/nfidd/sismid-nowcasting/blob/main/LICENSE).
